#!/usr/bin/env bash

NC='\033[0m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
RED='\033[0;31m'

# create ~/.ejb directory if missing
if [ ! -d "~/.ejb" ]; then
  echo -e "${YELLOW}Creating ~/.ejb${NC}"
  mkdir ~/.ejb
else
  echo -e "${GREEN}~/.ejb is present${NC}"
fi

# check if git is installed
type git &> /dev/null
if [ $? -ne 0 ];then
  echo -e "${RED}ERROR: git is not installed${NC}"
  echo "Install git and then rerun this script"
  exit 1
fi

# navigate into directory and clone if missing
cd ~/.ejb
if [ ! -d "dotfiles" ];then
  echo -e "${YELLOW}Cloning dotfiles repo${NC}"
  git clone https://github.com/evanjbowling/dotfiles.git
else
  echo -e "${GREEN}~/.ejb/dotfiles repo is present${NC}"
  echo -e "${YELLOW}Updating dotfiles repo${NC}"
  cd dotfiles
  git fetch && git pull
fi

# check if failure occurred with git updates
if [ $? -ne 0 ];then
  echo -e "${RED}ERROR: git update encountered error${NC}"
  exit 1
fi

echo -e "${GREEN}Installed${NC}"
cd ~/.ejb/dotfiles

# TODO: run separate installer within dotfiles repo
